# Generated by Django 6.0 on 2026-01-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_discount_tax_order_discount_order_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('usd', 'USD'), ('eur', 'EUR')], default='usd', max_length=3, verbose_name='Валюта'),
        ),
    ]
